<?php
  $DB_INFO = array(
      'db_name' => 'KGAUGER_BARRETOWNFOREST',
      'reader' => array( 'username' => 'kgauger_reader', 'password' => 'PgeDlSghV65pNePl' ),
      'writer' => array( 'username' => 'kgauger_writer', 'password' => 'uTyF4FTcqaY9jpS0' ),
      'admin'  => array( 'username' => 'kgauger_admin',  'password' => '3Hoj05MtusWRyX5L' ),
  );
  $SSL_INFO = array(
      'passphrase' => 'kmoose3991',
  );
?>